[package]
name = "cloth_bumpmap"
version = "0.1.0"
authors = ["jekto_vatimeliju <jekto.vatimeliju@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
description = "Creates a bump map used in the clothify algorithm in GIMP (GNU Image Manipulation Program)."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
rand = "0.7.3"
rand_distr = "0.2.2"
num = "0.2.1"
fastblur = "0.1.1"